# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'metro_maps' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod "Macaw", "0.9.7"
    pod 'HEREMaps' 
    pod 'RealmSwift'
  # Pods for metro_maps

end
